/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container":           "#93000a",
        "surface-tint":                 "#3b6934",
        "inverse-surface":              "#2e3130",
        "on-surface":                   "#191c1b",
        "on-secondary":                 "#ffffff",
        "on-primary-fixed-variant":     "#23501e",
        "surface-dim":                  "#d8dad9",
        "inverse-on-surface":           "#eff1ef",
        "on-primary-fixed":             "#002201",
        "on-tertiary-fixed":            "#1c1c11",
        "background":                   "#f8faf8",
        "surface-container-highest":    "#e1e3e1",
        "on-error":                     "#ffffff",
        "surface-bright":               "#f8faf8",
        "on-primary-container":         "#9fd292",
        "secondary":                    "#775a19",
        "surface":                      "#f8faf8",
        "primary-container":            "#2f5c28",
        "secondary-fixed":              "#ffdea5",
        "surface-container-low":        "#f2f4f2",
        "on-primary":                   "#ffffff",
        "on-tertiary-fixed-variant":    "#48473a",
        "surface-container-lowest":     "#ffffff",
        "on-secondary-container":       "#785a1a",
        "primary-fixed":                "#bcf0ae",
        "on-secondary-fixed":           "#261900",
        "outline":                      "#717a6d",
        "on-tertiary-container":        "#c8c5b3",
        "primary-fixed-dim":            "#a1d494",
        "inverse-primary":              "#a1d494",
        "surface-container":            "#eceeec",
        "outline-variant":              "#c0c9bb",
        "tertiary":                     "#3c3b2e",
        "primary":                      "#174413",
        "error":                        "#ba1a1a",
        "error-container":              "#ffdad6",
        "surface-variant":              "#e1e3e1",
        "tertiary-container":           "#535244",
        "tertiary-fixed":               "#e6e3d0",
        "surface-container-high":       "#e6e9e7",
        "on-tertiary":                  "#ffffff",
        "on-secondary-fixed-variant":   "#5d4201",
        "on-surface-variant":           "#41493e",
        "secondary-container":          "#fed488",
        "secondary-fixed-dim":          "#e9c176",
        "tertiary-fixed-dim":           "#c9c7b5",
        "on-background":                "#191c1b",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg:      "2rem",
        xl:      "3rem",
        full:    "9999px",
      },
      keyframes: {
        slideUp: {
          from: { opacity: 0, transform: "translateY(12px)" },
          to:   { opacity: 1, transform: "translateY(0)" },
        },
      },
      animation: {
        slideUp: "slideUp 0.25s ease-out",
      },
    },
  },
  plugins: [],
};
